/**
  @file    sound.h
  @author  ivansandrk
  @date    Mar 2013
  @version 0.1
  @brief   Sound code.
  
  Uses SDL_mixer which is a wrapper around SDL_audio which is yet a wrapper around OpenAL.
*/

#ifndef SOUND_H
#define SOUND_H

// sound_list and enums SOUND_* have to be in the same order
enum {SOUND_1006, SOUND_1017, SOUND_1028, SOUND_1036, SOUND_1041, SOUND_1045, SOUND_1049, SOUND_1055, SOUND_1059, SOUND_1062, SOUND_1074, SOUND_2MUCPAIN, SOUND_ALARM10, SOUND_ALARM11, SOUND_ALARM12, SOUND_ALARM13, SOUND_ALARM1, SOUND_ALARM2, SOUND_ALARM3, SOUND_ALARM4, SOUND_ALARM5, SOUND_ALARM6, SOUND_ALARM7, SOUND_ALARM8, SOUND_ALARM9, SOUND_ALLRITE, SOUND_ASSKILL, SOUND_BACKUP1, SOUND_BACKUP, SOUND_BEEP, SOUND_BEEPS, SOUND_BMBSTOP1, SOUND_BMBSTOP2, SOUND_BMBTHRW1, SOUND_BMBTHRW3, SOUND_BMBTHRW4, SOUND_BMBTHRW5, SOUND_BMDROP1, SOUND_BMDROP2, SOUND_BMDROP3, SOUND_BOING1, SOUND_BOING2, SOUND_BOMB_01, SOUND_BOMB_02, SOUND_BOMB_03, SOUND_BOMB_04B, SOUND_BOMB_04, SOUND_BOMB_05, SOUND_BOMB_06, SOUND_BOMB_07B, SOUND_BOMB_07, SOUND_BOMB_08, SOUND_BOMB_09, SOUND_BOMB_10, SOUND_BOMB10, SOUND_BOMB_11, SOUND_BOMB11, SOUND_BOMB_12B, SOUND_BOMB12B, SOUND_BOMB_12, SOUND_BOMB12, SOUND_BOMB_13, SOUND_BOMB13, SOUND_BOMB_14, SOUND_BOMB14, SOUND_BOMB_15B, SOUND_BOMB15B, SOUND_BOMB_15, SOUND_BOMB15, SOUND_BOMB_16, SOUND_BOMB16, SOUND_BOMB_17, SOUND_BOMB17, SOUND_BOMB_18, SOUND_BOMB18, SOUND_BOMB_19, SOUND_BOMB19, SOUND_BOMB1, SOUND_BOMB_20, SOUND_BOMB20, SOUND_BOMB_21B, SOUND_BOMB21B, SOUND_BOMB_21, SOUND_BOMB21, SOUND_BOMB_22, SOUND_BOMB22, SOUND_BOMB_23, SOUND_BOMB23, SOUND_BOMB_24B, SOUND_BOMB24B, SOUND_BOMB_24, SOUND_BOMB24, SOUND_BOMB2, SOUND_BOMB3, SOUND_BOMB4B, SOUND_BOMB4, SOUND_BOMB5, SOUND_BOMB6, SOUND_BOMB7B, SOUND_BOMB7, SOUND_BOMB8, SOUND_BOMB9, SOUND_BOMBBOUN, SOUND_BOMBHIT1, SOUND_BOMBHIT2, SOUND_BOMBHIT3, SOUND_BOMBHIT4, SOUND_BOMBSTOP, SOUND_BRAKHEAD, SOUND_BRINGON, SOUND_BURNEDUP, SOUND_BUSTASS, SOUND_CALLDAD, SOUND_CLEAR, SOUND_CLIKPLAT, SOUND_COMEGET, SOUND_COOLPOP, SOUND_CRIBROWN, SOUND_CUL8R, SOUND_DABOMB, SOUND_DESTU1, SOUND_DESTU2, SOUND_DIE1, SOUND_DIS2A, SOUND_DISEASE1, SOUND_DISEASE2, SOUND_DISEASE3, SOUND_DRABOM, SOUND_DRAW, SOUND_EATDUST, SOUND_ELAUGH1, SOUND_ENRT1, SOUND_ENRT2, SOUND_EWTAHH, SOUND_EXPL6, SOUND_EXPLO1, SOUND_EXPLODE2, SOUND_EXPLODE3, SOUND_EXPLODE4, SOUND_FEELPOWR, SOUND_FILLCRAK, SOUND_FIREINH, SOUND_GEN8A, SOUND_GET1, SOUND_GET2, SOUND_GODHERE, SOUND_GOTAHURT, SOUND_GOTCHA, SOUND_GRAB1, SOUND_GRAB2, SOUND_GUMP1, SOUND_HAILGON, SOUND_HITSTRID, SOUND_HURRY, SOUND_HURYTUF, SOUND_INZONE, SOUND_JESUS, SOUND_JJFM1, SOUND_JJFM2, SOUND_JJFM3, SOUND_JJFM4A, SOUND_JJFM4B, SOUND_JJFM5, SOUND_JJFM8, SOUND_JMB10, SOUND_JMB11, SOUND_JMB12, SOUND_JMB14, SOUND_JMB15, SOUND_JMB16, SOUND_JMB1, SOUND_JMB2, SOUND_JMB3, SOUND_JMB4, SOUND_JMB5, SOUND_JMB6, SOUND_JMB7, SOUND_JMB8, SOUND_JMB9, SOUND_JOFM1, SOUND_JOFM2, SOUND_KBOMB1, SOUND_KBOMB2, SOUND_KICKER10, SOUND_KICKER3, SOUND_KISSWOOK, SOUND_LATER, SOUND_LETTER1, SOUND_LETTER2, SOUND_LITEMUP, SOUND_LOOKOUT, SOUND_LOSE, SOUND_LOVNIT1, SOUND_LUVYAP, SOUND_MENUEXIT, SOUND_MENU, SOUND_MOLASES, SOUND_MYASS1, SOUND_NETWORK, SOUND_OHHHH, SOUND_OHNO1, SOUND_OHYEAH, SOUND_PACKIN, SOUND_PGAD12B, SOUND_PLAYPROP, SOUND_POOPS1, SOUND_POOPS2, SOUND_POOPS3, SOUND_POOPS4, SOUND_POOPS5, SOUND_PROUD, SOUND_QUITGAME, SOUND_ROASTED, SOUND_RUNAWAY1, SOUND_RUNAWAY2, SOUND_SCHWING, SOUND_SCREAM1, SOUND_SERENDIP, SOUND_SHAKEBOO, SOUND_SMELSMOK, SOUND_SQRDROP2, SOUND_SQRDROP4, SOUND_SQRDROP5, SOUND_SQRDROP6, SOUND_SQRDROP7, SOUND_SQRDROP8, SOUND_SQRDRPS2, SOUND_SQRDRPS3, SOUND_STUPIDIO, SOUND_SUCKITDN, SOUND_TASTPAI2, SOUND_TASTPAIN, SOUND_THEMAN, SOUND_TOEASY, SOUND_TRAMPO, SOUND_TRANSIN, SOUND_TRANSOUT, SOUND_WANTMNKY, SOUND_WARP1, SOUND_WHATRUSH, SOUND_WHODAD, SOUND_WIN, SOUND_WLKTAL1, SOUND_WLKTAL2, SOUND_WOOHOO1, SOUND_YEEHAW, SOUND_YOASSGRS, SOUND_YOUBLOW, SOUND_YOUWIN1, SOUND_ZEN1, SOUND_ZEN2,
      SOUND_LAST,
      SOUNDS_ERROR, SOUNDS_BOMB_DROP, SOUNDS_BOMB_KICK, SOUNDS_BOMB_STOP, SOUNDS_BOMB_JELLY_BOUNCE, SOUNDS_TILE_SLAM,
      SOUNDS_BOMB_PUNCH, SOUNDS_BOMB_FLYING_BOUNCE, SOUNDS_BOMB_GRAB, SOUNDS_BOMB_EXPLODE, SOUNDS_DIE_FLAMES, SOUNDS_WINNER,
      SOUNDS_DEATH_ANIM, SOUNDS_STEP_TRAMPOLINE, SOUNDS_STUNNED, SOUNDS_GOOD_POWERUP, SOUNDS_POOP, SOUNDS_TAUNT,
      SOUNDS_STRING, SOUNDS_AWESOME, SOUNDS_HURRY, 
      SOUNDS_LAST
};

int sound_init();
int sound_quit();
int sound_play(int sound);
int sound_play_loop(int sound);
int sound_stop_loop(int sound);

#endif /* SOUND_H */
